name: live_map_display
description: "An offline map"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:  
  flutter:
    sdk: flutter
  
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.4+4
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  location: ^8.0.0
  cupertino_icons: ^1.0.8
  flutter_map_mbtiles: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fake_cord_data.txt
  
